- app/src/main/java/info/blockchain/wallet/ReceiveFragment.java
- app/src/main/java/info/blockchain/wallet/SendFragment.java
SendFragment and ReceiveFragment code organised into separate methods. Some var names refactored.
> Send receive cleanup

- app/src/main/java/info/blockchain/wallet/AccountEditActivity.java
- app/src/main/java/info/blockchain/wallet/ReceiveFragment.java
- app/src/main/res/layout/activity_account_edit.xml
- app/src/main/res/layout/alert_show_extended_public_key.xml
- app/src/main/res/values/strings.xml
Contains UI updates related to account/address editor.
> Account editor

- app/src/main/AndroidManifest.xml
- app/src/main/java/piuk/blockchain/android/LauncherActivity.java
Fix for issue where the app could get stuck in a back button loop after parsing a bitcoin URI
> fix(Launcher Activity) fix backstack issues when scanning a URI

- app/src/main/java/piuk/blockchain/android/ui/account/AccountActivity.java
- app/src/main/java/piuk/blockchain/android/ui/account/AccountAdapter.java
- app/src/main/java/piuk/blockchain/android/ui/account/AccountItem.java
- app/src/main/java/piuk/blockchain/android/ui/base/BaseAuthActivity.java
- app/src/main/java/piuk/blockchain/android/ui/home/BalanceFragment.java
- app/src/main/res/drawable/ic_add.xml
- app/src/main/res/layout/activity_accounts.xml
- app/src/main/res/layout/activity_accounts_row.xml
- app/src/main/res/layout/activity_accounts_row_buttons.xml
- app/src/main/res/layout/txs_layout_expandable.xml
- Fix issue with balances being cut off by FAB
- Added some selectors to home and account list rows
> Bug fix/hidden totals

- app/src/main/java/piuk/blockchain/android/data/datamanagers/AuthDataManager.java
- app/src/main/java/piuk/blockchain/android/data/datamanagers/TransactionListDataManager.java
- app/src/main/java/piuk/blockchain/android/ui/auth/CreateWalletFragment.java
- app/src/main/java/piuk/blockchain/android/ui/auth/PinEntryActivity.java
- app/src/main/java/piuk/blockchain/android/ui/auth/PinEntryViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/backup/BackupWalletWordListFragment.java
- app/src/main/java/piuk/blockchain/android/ui/balance/BalanceViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainViewModel.java
- app/src/main/res/layout/fragment_backup_word_list.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/piuk/blockchain/android/data/datamanagers/AuthDataManagerTest.java
- app/src/test/java/piuk/blockchain/android/data/datamanagers/TransactionListDataManagerTest.java
- app/src/test/java/piuk/blockchain/android/ui/auth/PinEntryViewModelTest.java
- Disallow PIN reuse
- Fix crash when navigating away from create wallet screen
- Fix 2FA prompt showing twice
- Show email verification prompt after pairing with unverified email
- Show email verification prompt after recovering funds
- Fix issue where backup prompt wouldn't display after first transaction
- Fix issue where previous word button was available on backup word 1 causing crash
> Bug fixes/regression fixes

- app/build.gradle
- app/src/main/java/piuk/blockchain/android/ui/account/AccountEditViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/balance/BalanceFragment.java
- app/src/main/java/piuk/blockchain/android/ui/balance/BalanceViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/chooser/AccountChooserActivity.java
- app/src/main/java/piuk/blockchain/android/ui/chooser/AccountChooserViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/contacts/list/ContactsListActivity.java
- app/src/main/java/piuk/blockchain/android/ui/contacts/list/ContactsListViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/receive/ReceiveFragment.java
- app/src/main/java/piuk/blockchain/android/util/PermissionUtil.java
- app/src/main/res/drawable/vector_wallet.xml
- app/src/main/res/layout/activity_contacts.xml
- app/src/main/res/layout/fragment_receive.xml
- app/src/test/kotlin/piuk/blockchain/android/Assertions.kt
- app/src/test/kotlin/piuk/blockchain/android/ui/chooser/AccountChooserViewModelTest.kt
- app/src/test/kotlin/piuk/blockchain/android/ui/contacts/list/ContactsListViewModelTest.kt
Add BuildConfig field for enabling/disabling Contacts as appropriate. A few minor UI fixes included.
> Disable Contacts flag

- app/src/main/java/piuk/blockchain/android/ui/base/BaseAuthActivity.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsFragment.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsViewModel.java
- app/src/main/java/piuk/blockchain/android/util/PersistentPrefs.java
- app/src/main/java/piuk/blockchain/android/util/PrefsUtil.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- app/src/test/java/piuk/blockchain/android/ui/settings/SettingsViewModelTest.java
Allow users to toggle screenshot functionality. Disabled by default for security reasons.
> Screenshot Toggle

- app/src/main/java/piuk/blockchain/android/data/datamanagers/PayloadDataManager.java
- app/src/main/java/piuk/blockchain/android/data/datamanagers/TransferFundsDataManager.java
- app/src/main/java/piuk/blockchain/android/ui/account/AccountEditViewModel.java
- app/src/test/java/piuk/blockchain/android/data/datamanagers/SettingsDataManagerTest.java
- app/src/test/java/piuk/blockchain/android/ui/account/AccountEditViewModelTest.java
Fixed commented out test. Coverage back up to 48%
> test(AccountEditViewModel): Fix missing test

- app/src/main/java/piuk/blockchain/android/ui/fingerprint/FingerprintHelper.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsFragment.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsViewModel.java
- app/src/test/java/piuk/blockchain/android/ui/settings/SettingsViewModelTest.java
Removed a step in setting up fingerprint auth if you choose to do it from settings.
> Quicker fingerprint setup

- app/src/main/java/piuk/blockchain/android/ui/balance/BalanceFragment.java
- app/src/main/java/piuk/blockchain/android/ui/balance/BalanceViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
- app/src/main/res/layout/include_no_transaction_message.xml
- app/src/main/res/values/strings.xml
This will add a 'Get Bitcoin' button on the empty transactions screen.
SEPA user will be directed to buy bitcoin.
Non-SEPA users will be directed to receive bitcoin via QR.
> feat(Buy): Add get bitcoin link to empty transactions screen.

- app/build.gradle
- app/src/main/assets/licenses.html
- app/src/main/java/piuk/blockchain/android/injection/ApiModule.java
- build.gradle
Lots of dependencies have been added/removed, so this amends their licenses as necessary.
> chore(Licenses): Update licenses

- app/src/main/java/piuk/blockchain/android/data/access/AccessState.java
- app/src/main/java/piuk/blockchain/android/ui/chooser/AccountChooserViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/contacts/detail/ContactDetailFragment.java
- app/src/main/java/piuk/blockchain/android/ui/contacts/detail/ContactDetailViewModel.java
- app/src/main/java/piuk/blockchain/android/ui/send/SendViewModel.java
- app/src/test/kotlin/piuk/blockchain/android/ui/chooser/AccountChooserViewModelTest.kt
- app/src/test/kotlin/piuk/blockchain/android/ui/contacts/detail/ContactDetailViewModelTest.kt
Refactor to use AccessState everywhere, remove shared prefs calls
> Bitcoin Viewtype Settings

- circle.yml
In theory caching of the SDK in Circle should work a little better now
> chore(CircleCI): Correct caching

- app/src/main/java/piuk/blockchain/android/ui/auth/LandingActivity.kt
- app/src/main/java/piuk/blockchain/android/ui/auth/LandingPresenter.kt
- app/src/main/java/piuk/blockchain/android/ui/auth/LandingView.kt
- app/src/main/res/layout/activity_landing.xml
This was way more fiddly than I expected.
> refactor(Landing): Convert landing activity to ConstraintLayout

- app/build.gradle
- app/src/main/java/piuk/blockchain/android/ui/auth/EnvironmentSwitcher.java
Use initWith to inherit most settings from release build. Add reset wallet button to debug settings because I miss being able to quickly wipe a wallet from there.
> Gradle cleanup

- app/src/main/java/piuk/blockchain/android/ui/send/PendingTransaction.java
- app/src/main/java/piuk/blockchain/android/ui/send/SendPresenter.kt
No more state to maintain on address selection or payment completion.
> Fix(Send): Change watch-only spend to cleaner solution.

- app/build.gradle
- build.gradle
Add kapt for annotation processing in Kotlin, update dependencies. Mostly done to silence some nagging in the Gradle console.
> chore(kapt)

- app/src/main/java/piuk/blockchain/android/data/answers/Logging.kt
- app/src/main/java/piuk/blockchain/android/ui/auth/PinEntryPresenter.java
- app/src/test/java/piuk/blockchain/android/ui/auth/PinEntryPresenterTest.java
- build.gradle
Fix issue where uncaught exception type could cause wallets to unpair unexpectedly
> Server Timeout

- app/src/main/java/piuk/blockchain/android/ui/receive/WalletAccountHelper.kt
AND-1187
Issue: java.lang.IllegalStateException: payloadManager.payload must not be null
Following the approach we used on getHDAccounts() I added checking if payload is null, and then use an empty list. This is to avoid the crash in case that walletBaseBody is null, as we are returning null in PayloadManager->getPayLoad()
> fix(Fabric issue) AND-1187 #1449 Issue: java.lang.IllegalStateException: payloadManager.payload must not be null

- app/src/main/res/values/strings.xml
AND-1250 This is fixing only the English translation, I will create a new ticket for the rest.
> fix(Translations): AND-1250 Fix wallet pairing copy

- app/src/main/java/piuk/blockchain/android/ui/balance/BalancePresenter.kt
- app/src/main/java/piuk/blockchain/android/ui/balance/adapter/TxFeedAdapter.kt
- app/src/test/java/piuk/blockchain/android/ui/balance/BalancePresenterTest.kt
- buysellui/src/main/res/values/strings.xml
- core/src/main/java/piuk/blockchain/androidcore/data/transactions/models/TransactionDtos.kt
- core/src/test/java/piuk/blockchain/androidcore/data/transactions/models/DisplayableTest.kt
There's undeniably some nastiness in here, but I'm looking to completely overhaul transaction handling in the near future.
> Adam/and 1256/coinify transaction labels

- app/src/main/java/piuk/blockchain/android/ui/buysell/details/trade/CoinifyTransactionDetailActivity.kt
- app/src/main/java/piuk/blockchain/android/ui/buysell/overview/CoinifyOverviewPresenter.kt
- app/src/main/java/piuk/blockchain/android/ui/buysell/overview/adapter/BuySellTransactionDelegate.kt
- app/src/main/res/layout/activity_coinify_transaction_detail.xml
- buysellui/src/main/res/values/strings.xml
Fixes conflict in `strings.xml`
> Adam/and 1263/move cta to bottom of page

- buildSrc/src/main/java/Dependencies.kt
> chore(Versioning): AND-1264 Increment version codes for release

- app/src/main/java/piuk/blockchain/android/ui/balance/adapter/DisplayableDelegate.kt
- app/src/main/java/piuk/blockchain/android/ui/contacts/detail/ContactDetailPresenter.java
- app/src/main/java/piuk/blockchain/android/ui/transactions/TransactionDetailPresenter.java
- balance/src/main/kotlin/info/blockchain/balance/CryptoCurrency.kt
- balance/src/test/kotlin/info/blockchain/balance/CryptoCurrencyTests.kt
- Consolidated repeated constants.
- Added tests.
> fix(BCH Confirmations): AND-1285 BCH requires 3 confirmations

- app/src/main/java/piuk/blockchain/android/BlockchainApplication.java
- app/src/main/java/piuk/blockchain/android/injection/ServiceModule.java
- app/src/test/java/piuk/blockchain/android/ui/receive/ReceivePresenterTest.kt
- app/src/test/java/piuk/blockchain/android/ui/shapeshift/confirmation/ShapeShiftConfirmationPresenterTest.kt
- wallet/src/integrationTest/java/info/blockchain/wallet/BaseIntegTest.java
- wallet/src/main/java/info/blockchain/wallet/BlockchainFramework.java
- wallet/src/main/java/info/blockchain/wallet/FrameworkInterface.java
- wallet/src/main/java/info/blockchain/wallet/shapeshift/ShapeShiftApi.java
- wallet/src/test/java/info/blockchain/wallet/MockedResponseTest.java
- wallet/src/test/java/info/blockchain/wallet/contacts/ContactsTest.java
- wallet/src/test/java/info/blockchain/wallet/metadata/MetadataNodeFactoryTest.java
- wallet/src/test/java/info/blockchain/wallet/metadata/MetadataTest.java
- wallet/src/test/java/info/blockchain/wallet/shapeshift/ShapeShiftApiTest.java
- wallet/src/test/java/info/blockchain/wallet/util/FormatsUtilTest.java
To remove a barrier to moving from some shapeshift classes, plus injected now in same way as main wallet api.
> AND-1249 Shapeshift endpoints injection

- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/ExchangeDialog.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/Intents.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/Quote.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ApplyQuoteTest.kt
- Now we receive all the quote details, all I actually needed to change was adding a new intent.
- The intent will have all the data from the websocket (mapping from json to follow later).
> feat(HomeBrew): AND-1336 New MVI intent for receiving a whole quote

- app/src/main/java/com/blockchain/koin/KoinStarter.kt
- app/src/main/java/com/blockchain/koin/modules/morphMethodModule.kt
- app/src/main/java/piuk/blockchain/android/injection/ApplicationModule.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
- morph/common/src/main/java/com/blockchain/morph/MorphMethodSelector.kt
- For now debug -> HomeBrew, release -> ShapeShift.
> feat(HomeBrew): AND-1248 Allow directing of users to shapeshift or homebrew

- app/src/main/java/com/blockchain/koin/KoinStarter.kt
- app/src/main/java/com/blockchain/koin/modules/localShapeShift.kt
- app/src/main/java/com/blockchain/koin/modules/morphMethodModule.kt
- app/src/main/java/piuk/blockchain/android/injection/ContextModule.kt
- app/src/main/java/piuk/blockchain/android/ui/shapeshift/detail/ShapeShiftDetailActivity.kt
- app/src/main/java/piuk/blockchain/android/ui/shapeshift/detail/ShapeShiftDetailPresenter.kt
- morph/common/src/main/java/com/blockchain/morph/CoinPair.kt
- morph/common/src/main/java/com/blockchain/morph/trade/MorphTrade.kt
- morph/common/src/main/java/com/blockchain/morph/trade/MorphTradeDataManager.kt
- morph/common/src/main/java/com/blockchain/morph/trade/MorphTradeOrder.kt
- morph/common/src/main/java/com/blockchain/morph/trade/MorphTradeStatus.kt
- morph/common/src/test/java/com/blockchain/morph/CoinPairTest.kt
- morph/shapeshift/src/main/java/com/blockchain/koin/modules/shapeshiftModule.kt
- morph/shapeshift/src/main/java/piuk/blockchain/androidcore/data/shapeshift/ShapeShiftDataManager.kt
- morph/shapeshift/src/main/java/piuk/blockchain/androidcore/data/shapeshift/ShapeShiftDataManagerAdapter.kt
- morph/shapeshift/src/main/java/piuk/blockchain/androidcore/data/shapeshift/TradeAdapter.kt
- morph/shapeshift/src/main/java/piuk/blockchain/androidcore/data/shapeshift/TradeStatusResponseAdapter.kt
- morph/shapeshift/src/main/java/piuk/blockchain/androidcore/data/shapeshift/datastore/ShapeShiftDataStore.kt
- morph/shapeshift/src/test/java/piuk/blockchain/androidcore/data/shapeshift/ShapeShiftDataManagerTest.kt
- Part 1
- Breaking the dependencies of ShapeShift Detail presenter on ShapeShift TDOs, so can use same for HomeBrew
> feat(HomeBrew): AND-1344 Generalize shape shift trade detail activity

- buildSrc/src/main/java/Dependencies.kt
- morph/morphdevapp/build.gradle
- morph/morphdevapp/src/main/AndroidManifest.xml
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/MainActivity.kt
- morph/ui/build.gradle
- morph/ui/src/main/AndroidManifest.xml
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivity.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/IntegerKeyboardView.kt
- morph/ui/src/main/res/drawable/ic_backspace_exchange_blue_26dp.xml
- morph/ui/src/main/res/layout/activity_homebrew_exchange.xml
- morph/ui/src/main/res/layout/integer_keyboard.xml
- morph/ui/src/main/res/values/exchange_strings.xml
- morph/ui/src/main/res/values/exchange_styles.xml
- rough layout, can type fiat
- new integer keyboard control
> feat(HomeBrew): AND-1350 Add ExchangeActivity

- buildSrc/src/main/java/Dependencies.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/Intents.kt
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/App.kt
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/FakeRatesStream.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivity.kt
- morph/ui/src/main/res/drawable/ic_arrow_forward_exchange_blue_24dp.xml
- morph/ui/src/main/res/layout/activity_homebrew_exchange.xml
- Uses the Exchange MVI dialog.
- Uses simulated rates, defined in and injected in demo app
- Next step is to use fake quotes, which are different because they need to know the volume
> feat(HomeBrew): AND-1350 Show simulated rates on UI in demo app

- app/build.gradle
- app/src/main/java/com/blockchain/koin/modules/applicationModule.kt
- app/src/main/java/piuk/blockchain/android/injection/ApplicationModule.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsFragment.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsPresenter.java
- app/src/main/java/piuk/blockchain/android/ui/settings/SettingsView.java
- app/src/main/res/xml/settings.xml
- app/src/test/java/piuk/blockchain/android/ui/settings/SettingsPresenterTest.java
- kyc/proguard-rules.pro
- kyc/src/main/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManager.kt
- kyc/src/main/java/com/blockchain/kycui/settings/KycStatusHelper.kt
- kyc/src/main/java/com/blockchain/kycui/settings/KycStatusPreference.kt
- kyc/src/main/res/drawable/rounded_view_in_progress.xml
- kyc/src/main/res/layout/preference_identity_verification.xml
- kyc/src/main/res/values/colors.xml
- kyc/src/main/res/values/strings.xml
- kyc/src/test/java/com/blockchain/kycui/settings/KycStatusHelperTest.kt
> feat(Homebrew): AND-1236 Add settings entry

- app/src/main/java/com/blockchain/koin/modules/serviceModule.kt
- app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainPresenter.java
- app/src/main/java/piuk/blockchain/android/ui/home/MainView.java
- app/src/main/res/menu/menu_nav_drawer.xml
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/App.kt
- morph/ui/src/debug/java/com/blockchain/homebrew/FakeRatesStream.kt
- morph/ui/src/debug/java/com/blockchain/koin/debug.kt
- morph/ui/src/main/java/com/blockchain/koin/morphUiModule.kt
- morph/ui/src/main/res/values/strings.xml
- morph/ui/src/release/java/com/blockchain/koin/debug.kt
- wallet/src/main/java/com/blockchain/koin/walletModule.kt
Show the home brew exchange from the menu (debug build only).
> feat(HomeBrew): AND-1398 Expose homebrew exchange in debug mode

- app/src/main/java/com/blockchain/koin/modules/serviceModule.kt
- wallet/src/integrationTest/java/info/blockchain/wallet/api/WalletApiIntegTest.java
- wallet/src/integrationTest/java/info/blockchain/wallet/payload/PayloadManagerIntegTest.java
- wallet/src/main/java/info/blockchain/wallet/api/WalletApi.java
- wallet/src/test/java/info/blockchain/wallet/WalletApiMockedResponseTest.java
Just a little refactor that happened during trying to get Auth to work
> feat(HomeBrew): AND-1335 Wallet has API code injected

- coreui/src/main/java/com/blockchain/ui/extensions/ThrottledClicks.kt
- kyc/src/main/java/com/blockchain/kycui/address/KycHomeAddressFragment.kt
- kyc/src/main/java/com/blockchain/kycui/complete/ApplicationCompleteFragment.kt
- kyc/src/main/java/com/blockchain/kycui/mobile/entry/KycMobileEntryFragment.kt
- kyc/src/main/java/com/blockchain/kycui/mobile/validation/KycMobileValidationFragment.kt
- kyc/src/main/java/com/blockchain/kycui/navhost/KycNavHostActivity.kt
- kyc/src/main/java/com/blockchain/kycui/onfidosplash/OnfidoSplashFragment.kt
- kyc/src/main/java/com/blockchain/kycui/profile/KycProfileFragment.kt
Not very exciting, but should pop all pages when flow completed and redirect to the status page.
> feat(Homebrew): AND-1402 Fix back stack handling in KYC flow

- app/build.gradle
- balance/src/main/kotlin/info/blockchain/balance/CryptoValue.kt
- balance/src/test/kotlin/info/blockchain/balance/CryptoValueTests.kt
- build.gradle
- coreui/src/main/java/com/blockchain/balance/CryptoCurrencyColor.kt
- coreui/src/main/java/com/blockchain/balance/CryptoCurrencyImage.kt
- coreui/src/main/res/drawable/layer_list_bitcoin_cash.xml
- coreui/src/main/res/values/colors.xml
- kyc/build.gradle
- kyc/src/test/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManagerAsAuthenticatorTest.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivity.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivityConfigurationChangePersistence.kt
- morph/ui/src/main/res/layout/activity_homebrew_exchange.xml
- morph/ui/src/main/res/values/exchange_styles.xml
- morph/ui/src/test/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivityConfigurationChangePersistenceTest.kt
- BTC colour was already in app
- BCH colour from reddit community
- ETHER colour from our designs
- All Icons were already in the app
- When there is a value, the icon does not show
> feat(HomeBrew): AND-1374 Update the displayed crypto icons and colours

- common/network/src/main/kotlin/com/blockchain/network/EnvironmentUrls.kt
- common/network/src/main/kotlin/com/blockchain/network/modules/apiModule.kt
- common/network/src/test/kotlin/com/blockchain/network/websocket/OkHttpWebSocketConnectionEventTests.kt
- kyc/src/main/java/com/blockchain/injection/kycModule.kt
- kyc/src/main/java/com/blockchain/kyc/api/nabu/NabuApiConstants.kt
- kyc/src/main/java/com/blockchain/kyc/services/nabu/NabuService.kt
- kyc/src/test/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManagerAsAuthenticatorTest.kt
- nabu/src/main/kotlin/com/blockchain/koin/nabuModule.kt
- nabu/src/main/kotlin/com/blockchain/nabu/api/NabuMarkets.kt
- nabu/src/main/kotlin/com/blockchain/nabu/api/TradingConfig.kt
- nabu/src/main/kotlin/com/blockchain/nabu/models/NabuSessionTokenResponse.kt
- nabu/src/main/kotlin/com/blockchain/nabu/service/NabuMarketsService.kt
- nabu/src/test/kotlin/com/blockchain/nabu/service/MockAuthenticator.kt
- nabu/src/test/kotlin/com/blockchain/nabu/service/NabuMarketsServiceTest.kt
- nabu/src/test/kotlin/com/blockchain/nabu/service/apiServerTestModule.kt
- testutils/src/main/kotlin/com/blockchain/testutils/AssignableAssertions.kt
- testutils/src/test/kotlin/com/blockchain/testutils/AssignableAssertionsTest.kt
- Working authentication for endpoint
- The endpoint will probably change very soon once the new one is up (`trade/limits`)
> feat(HomeBrew): AND-1353 Add endpoint authentication

- common/network/src/main/kotlin/com/blockchain/network/websocket/AfterConnectionEventWebSocket.kt
- common/network/src/main/kotlin/com/blockchain/network/websocket/WebSocket.kt
- common/network/src/test/kotlin/com/blockchain/network/websocket/AfterAuthenticateWebSocketTest.kt
- common/network/src/test/kotlin/com/blockchain/network/websocket/RetryingConnectionTest.kt
- kyc/src/main/java/com/blockchain/kyc/datamanagers/nabu/NabuAuthenticator.kt
- kyc/src/main/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManager.kt
- kyc/src/test/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManagerAsAuthenticatorTest.kt
- morph/homebrew/build.gradle
- morph/homebrew/src/main/kotlin/com/blockchain/morph/homebrew/AuthWebSocket.kt
- morph/homebrew/src/test/kotlin/com/blockchain/morph/homebrew/AuthWebSocketTest.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/TimberWebSocket.kt
- nabu/src/main/kotlin/com/blockchain/nabu/Authenticator.kt
- nabu/src/test/kotlin/com/blockchain/nabu/service/MockAuthenticator.kt
Also:
- Timber extension for logging.
> feat(HomeBrew): AND-1339 Auth WebSocket

- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialog.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialogTest.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/FloatKeyboardView.kt
- morph/ui/src/main/res/layout/float_keyboard.xml
- The shake isn't hooked up, but TDD'd when to shake via MVI, I just need to switch to the `FloatKeyboard` from current `IntegerKeyboard` and subscribe to the view state changes
> feat(HomeBrew): AND-1430 Floating point keyboard with shake feedback

- morph/common/src/main/java/com/blockchain/morph/exchange/service/QuoteService.kt
- morph/ui/build.gradle
- morph/ui/src/main/java/com/blockchain/koin/morphUiModule.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeModel.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/confirmation/ExchangeConfirmationFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/host/HomebrewNavHostActivity.kt
Early days, but both fragments are sharing a "model", the model contains the socket.
> feat(HomeBrew): AND-1350 Live quotes on confirm screen

- app/src/main/res/layout/fragment_graphs.xml
- app/src/main/res/layout/item_asset_price_card.xml
- buildSrc/src/main/java/Dependencies.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/detail/HomebrewTradeDetailActivity.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/extensions/MorphStatusExtensions.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/history/TradeHistoryPresenter.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/history/adapter/TradeHistoryAdapter.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/model/Trade.kt
- morph/ui/src/main/res/layout/activity_homebrew_trade_detail.xml
- morph/ui/src/main/res/layout/activity_homebrew_trade_history.xml
- morph/ui/src/main/res/layout/activity_homebrew_trade_locked.xml
- morph/ui/src/main/res/values/strings.xml
> feat(Homebrew): AND-1386 Render real data on order detail page

- app/src/main/java/piuk/blockchain/android/ui/dashboard/adapter/PieChartDelegate.kt
- app/src/main/java/piuk/blockchain/android/ui/send/SendPresenter.kt
- balance/src/main/kotlin/info/blockchain/balance/CryptoCurrency.kt
- balance/src/main/kotlin/info/blockchain/balance/CryptoCurrencyFormatter.kt
- balance/src/main/kotlin/info/blockchain/balance/CryptoValue.kt
- balance/src/main/kotlin/info/blockchain/balance/ExchangeRate.kt
- balance/src/main/kotlin/info/blockchain/balance/FiatValue.kt
- balance/src/main/kotlin/info/blockchain/balance/LocaleDecimalFormat.kt
- balance/src/main/kotlin/info/blockchain/balance/Money.kt
- balance/src/test/kotlin/info/blockchain/balance/CryptoValuePartsTest.kt
- balance/src/test/kotlin/info/blockchain/balance/CryptoValueTests.kt
- balance/src/test/kotlin/info/blockchain/balance/FiatValuePartsTest.kt
- balance/src/test/kotlin/info/blockchain/balance/FiatValueTests.kt
- balance/src/test/kotlin/info/blockchain/balance/MoneyFormattingTests.kt
- balance/src/test/kotlin/info/blockchain/balance/MoneyMaxDecimalTests.kt
- balance/src/test/kotlin/info/blockchain/balance/TestHelpers.kt
- common/network/src/test/kotlin/com/blockchain/serialization/BigDecimalJsonTests.kt
- core/src/main/java/piuk/blockchain/androidcore/data/exchangerate/ExchangeRateDataManager.kt
- core/src/test/java/piuk/blockchain/androidcore/data/exchangerate/ExchangeRateDataManagerTest.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialog.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialogTest.kt
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/FakeQuoteService.kt
- morph/shapeshift/src/main/java/com/blockchain/morph/QuoteRequestMapper.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/FloatKeyboardView.kt
- The Crypto entry works differently to fiat
- There are still issues around this but this is much better than the version in develop
- Issues include:
- Doesn't resize font of value is getting large
- Doesn't always update where there are trailing zeros
> feat(HomeBrew): AND-1350 Keyboard Crypto Entry

- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
- morph/ui/src/main/res/layout/fragment_homebrew_exchange.xml
- morph/ui/src/main/res/values/exchange_strings.xml
> feat(HomeBrew): AND-1374 Exchange button text matches selected accounts

- app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/ExchangeDialog.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialog.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/Intents.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/service/TradeLimitService.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ApplyMaximumTradeLimit.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ApplyMinimumTradeLimit.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialogTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/InitialStateTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/SetTradeLimitsTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/TestHelpers.kt
- morph/morphdevapp/src/main/java/com/blockchain/morph/dev/MainActivity.kt
- morph/ui/src/main/java/com/blockchain/koin/morphUiModule.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeModel.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/confirmation/ExchangeConfirmationFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/confirmation/ExchangeConfirmationPresenter.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/confirmation/ExchangeConfirmationView.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/history/TradeHistoryActivity.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/host/HomebrewNavHostActivity.kt
- morph/ui/src/main/res/layout/fragment_homebrew_exchange.xml
- morph/ui/src/main/res/values/exchange_strings.xml
- morph/ui/src/main/res/values/exchange_styles.xml
- morph/ui/src/test/java/com/blockchain/morph/ui/homebrew/exchange/confirmation/ExchangeConfirmationPresenterTest.kt
- nabu/src/main/kotlin/com/blockchain/koin/nabuModule.kt
- nabu/src/main/kotlin/com/blockchain/nabu/service/NabuMarketsService.kt
- Working Min and Max buttons
- They do not yet apply the users max spendable balance however
> feat(HomeBrew): AND-1353 Working Min and Max buttons

- core/src/main/java/piuk/blockchain/androidcore/data/payload/PayloadDataManager.kt
- core/src/test/java/piuk/blockchain/androidcore/data/payload/PayloadDataManagerTest.kt
Same thing you did, really. Just moved slightly further up the stack where it's testable.
> fix(Metadata): AND-909 Ensure metadatanode exists before fetching, load if necessary.

- app/build.gradle
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- build.gradle
- buildSrc/src/main/java/Dependencies.kt
- kyc/build.gradle
Didn't really get anywhere with the QA build stuff - if anything the errors involved got more cryptic. But these changes seemed to glean a worthwhile performance boost, and are necessary for App Bundle support.
> chore(Homebrew): AND-1237 Migrate to AGP 3.2.0

- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialog.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/FloatKeyboardDialogTest.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/FloatKeyboardView.kt
- morph/ui/src/main/res/layout/fragment_homebrew_exchange.xml
- morph/ui/src/main/res/values/exchange_styles.xml
- to 11 significant figures or 999,999 whatever comes first
> feat(Homebrew): AND-1442 Resize font when gets long, also limit entry

- balance/src/main/kotlin/info/blockchain/balance/CryptoValue.kt
- balance/src/main/kotlin/info/blockchain/balance/FiatValue.kt
- balance/src/main/kotlin/info/blockchain/balance/Money.kt
- balance/src/test/kotlin/info/blockchain/balance/FiatValueTests.kt
- balance/src/test/kotlin/info/blockchain/balance/ToZeroTest.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/ExchangeDialog.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/Intents.kt
- morph/common/src/main/java/com/blockchain/morph/exchange/mvi/QuoteValidityExtensions.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ApplyQuoteTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ClearQuoteTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/QuoteMismatchExtensionTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/QuoteOutDatedExtensionTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/SwitchingAccountKeepingValueTest.kt
- morph/common/src/test/java/com/blockchain/morph/exchange/mvi/TestHelpers.kt
- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeModel.kt
- I expect to get a quote every few seconds if I don't see one for 10 seconds, I clear the displayed values
- If the user enters a value outside of the limits, the quote is cleared after a brief 250ms timeout
Covers AND-1482 AND-1461, except no user feedback still, missing quotes feedback will come under another ticket.
> feat(Homebrew): AND-1461 Listen for out of date quotes and clear the displayed values

- morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
> feat(Homebrew): AND-1479 Do not display values on the min and max buttons
