blockchain/My-Wallet-V3-Android

app/src/main/java/info/blockchain/wallet/MainActivity.java
app/src/main/java/info/blockchain/wallet/ReceiveFragment.java
app/src/main/java/info/blockchain/wallet/SendFragment.java
app/src/main/java/info/blockchain/wallet/util/MonetaryUtil.java

Removed force to US locale - This forced app to expect “.” as separator but devices keypad might only allow user to input “,”.
Custom keypad for samsung devices will now enter correct decimal separator.
TextWatcher will now detect separator of input text.
Decimal grouping symbol set to ‘ ‘ for easy readability.

Allow decimal separator based on locale.

---

app/src/main/java/info/blockchain/wallet/SendFragment.java

- After scanning private key for watch-only spend confirmation, selectDefaultAccount() was called after returning from qr scan activity, which updated the coin selection just before transaction signing needed to happen.

Default account should only be selected onCreate, not onResume.

---

app/build.gradle
app/src/test/java/info/blockchain/wallet/datamanagers/AuthDataManagerTest.java
app/src/test/java/info/blockchain/wallet/pairing/PairingTest.java
app/src/test/java/info/blockchain/wallet/viewModel/ManualPairingViewModelTest.java
app/src/test/java/info/blockchain/wallet/viewModel/PasswordRequiredViewModelTest.java
app/src/test/java/piuk/blockchain/android/LauncherViewModelTest.java

- Legacy Apache classes were being specifically kept, but aren't being used anymore
- Fixes for unit tests failing intermittently; some state was being stored in the Application class somehow
- Added verbose test output in prep for CI

Fixes for flaky unit tests, removed legacy Apache stuff from Gradle

---

app/src/main/java/piuk/blockchain/android/data/datamanagers/TransactionListDataManager.java
app/src/main/java/piuk/blockchain/android/ui/account/AccountEditActivity.java
app/src/main/java/piuk/blockchain/android/ui/account/AccountEditViewModel.java
app/src/main/java/piuk/blockchain/android/ui/home/MainActivity.java
app/src/main/java/piuk/blockchain/android/ui/receive/ReceiveCurrencyHelper.java
app/src/main/java/piuk/blockchain/android/ui/send/SendViewModel.java
app/src/test/java/piuk/blockchain/android/data/datamanagers/AccountDataManagerTest.java
app/src/test/java/piuk/blockchain/android/ui/account/AccountEditViewModelTest.java
app/src/test/java/piuk/blockchain/android/ui/transactions/TransactionDetailViewModelTest.java

- Fix issue where changing default account and then quitting the app wouldn't update swipe to receive or launcher shortcut addresses
- Fix issue where Tx list detail could show different transactions
- Fix issue where wrong bottom nav icon could be highlighted after returning to the app
- Fix issue where users couldn't enter 5 digits of mBTC after decimal point
- Fix failing tests

Bug fix/prerelease 01 30 2017

---

app/src/main/java/piuk/blockchain/android/ui/base/BaseAuthActivity.java
app/src/main/java/piuk/blockchain/android/util/AndroidUtils.java

Fix issue where pressing the back button in the ActionBar on API 15, 16 & 17 would throw an IllegalArgumentException. If setting custom fonts in Android, any MenuItem selected events log the value of the ActionBar title, which doesn’t handle custom fonts (applied via Spannable) on the affected versions and crashes instead.
See here for more info: https://android-review.googlesource.com/#/c/47831/

Fix for ActionBar bug

---

app/src/main/java/piuk/blockchain/android/ui/send/SendFragment.java

Added a on text change listener to invalidate receive address kept in memory after scanning a receive address. Some devices ignore the on click listener that was put in place to prevent this behaviour.

fix(Send): Invalidate receiving address after user edits field.

---

.gitignore
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/piuk/blockchain/android/BlockchainApplication.java

Since Google has [acquired the team at Fabric](https://fabric.io/blog/fabric-joins-google/), they have now deprecated the Firebase crash reporting suite that we've been using for a while in favour of Crashlytics, which is soon to be integrated fully into the Firebase panel. Crashlytics is hugely better and more flexible, so this is a welcome development.
If anyone from the team wants access to the crash reporting panel, message myself or Riaan and we can invite you to the project.

chore(Crashlytics): Remove Firebase crash reporting for Crashlytics

---

app/src/main/java/piuk/blockchain/android/data/services/ExchangeService.java

_Problem_
After the web wallet saves data to the metadata service, if the web view is closed and reopened, Android will fetch the new metadata, but will not get the new magic hash. Android then passes an incorrect magic has to the web wallet, causing saves to metadata to not work.
_Solution_
Fetch the latest magic hash before passing it to the web wallet.
I'm not sure this is the best way to do this, I think it might be better to fix this in v3-jar. I tried making it so the magic hash will update automatically during calls to Metadata::getMetadata, but couldn't get that to work. Let me know if you have any ideas @ditn @riaanjvos

Refresh magic hash when loading exchange data

---

app/src/main/java/piuk/blockchain/android/ui/buy/BuyActivity.java

This fixes the issue where pressing the "back" button will open blockchain.info in the phone's browser, on some phones. I think what was happening is that the teardown() function was making a redirect, which is sometimes intercepted by Android. Teardown() is really just to refresh the page, this changes it so that the web view is refreshed directly, preventing any redirect.

Prevent redirecting to browser when buy is closed

---

app/src/main/java/piuk/blockchain/android/data/exchange/CoinifyData.java
app/src/main/java/piuk/blockchain/android/data/exchange/ExchangeData.java
app/src/main/java/piuk/blockchain/android/data/exchange/SfoxData.java
app/src/main/java/piuk/blockchain/android/data/exchange/TradeData.java
app/src/main/java/piuk/blockchain/android/data/services/ExchangeService.java

There was an issue with mapping exchange data JSON to java objects. I couldn't reproduce on any of the phones I tried, but from what I've read it seems like the issue could be missing default constructors. Would that make sense? Error message in the ticket contains:
```java
06-14 13:51:26.216 8012-8012/? W/System.err: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class piuk.blockchain.android.data.exchange.CoinifyData]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
```
I'm also filtering out sell trades now, since those don't need to be watched.

Fix - Buy trades

---

app/src/main/AndroidManifest.xml

Fix issue where re-entering the app from the launcher icon would restart the app completely, which isn't a problem if you're already logged in but could prevent login under certain conditions.
Please give this one a test, I'm not 100% certain that this can't introduce weird multi-instance/activity backstack bugs but I've not seen anything in my testing.

fix(Single Task)

---

wallet/src/test/java/info/blockchain/wallet/MockedResponseTest.java

The cause of the flakey tests I think was this base setup method was never called due to being overridden. Sometimes they passed when another test ran earlier that successfully set the blockchain framework.
No doubt we still want to improve this so that we don't have a static init method as part of AND-1184 but this should stop the failures for now.

AND-1186 Rename base @Before method that was being hidden

---

app/src/main/java/piuk/blockchain/android/ui/buysell/confirmation/sell/CoinifySellConfirmationPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/buysell/createorder/BuySellBuildOrderPresenter.kt

`putCurrency(Currency.getInstance("BTC")` is actually just `putCustomAttribute("currency", "BTC")` under the hood, so we can replace `Currency.getInstance("BTC")`, as this throws an `IllegalArgumentException` on some Android versions and blocks Sell.

fix(Logging): AND-1173 

---

app/src/main/java/piuk/blockchain/android/ui/account/AccountEditPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/account/AccountPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/backup/transfer/ConfirmFundsTransferPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/buysell/createorder/BuySellBuildOrderPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/charts/ChartsPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/chooser/AccountChooserPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/contacts/detail/ContactDetailPresenter.java
app/src/main/java/piuk/blockchain/android/ui/dashboard/DashboardPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/receive/ReceivePresenter.kt
app/src/main/java/piuk/blockchain/android/ui/send/SendPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/shapeshift/newexchange/NewExchangePresenter.kt
app/src/main/java/piuk/blockchain/android/ui/shapeshift/overview/ShapeshiftPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/transactions/TransactionDetailPresenter.java
app/src/test/java/piuk/blockchain/android/ui/account/AccountEditPresenterTest.kt
app/src/test/java/piuk/blockchain/android/ui/account/AccountPresenterTest.kt
app/src/test/java/piuk/blockchain/android/ui/backup/transfer/ConfirmFundsTransferPresenterTest.kt
app/src/test/java/piuk/blockchain/android/ui/charts/ChartsPresenterTest.kt
app/src/test/java/piuk/blockchain/android/ui/contacts/detail/ContactDetailPresenterTest.kt
app/src/test/java/piuk/blockchain/android/ui/receive/ReceivePresenterTest.kt
balance/src/main/kotlin/info/blockchain/balance/CryptoValue.kt
core/src/main/java/piuk/blockchain/androidcore/data/currency/CurrencyFormatManager.kt
core/src/main/java/piuk/blockchain/androidcore/data/currency/CurrencyFormatUtil.kt
core/src/main/java/piuk/blockchain/androidcore/data/exchangerate/ExchangeRateDataManager.kt
core/src/main/java/piuk/blockchain/androidcore/data/exchangerate/datastore/ExchangeRateDataStore.kt
core/src/test/java/piuk/blockchain/androidcore/data/currency/CurrencyFormatManagerTest.kt
core/src/test/java/piuk/blockchain/androidcore/data/currency/CurrencyFormatUtilTest.kt
core/src/test/java/piuk/blockchain/androidcore/data/exchangerate/ExchangeRateDataManagerTest.kt

- Replace repeated price and format code with code that uses CryptoCurrency enum. 
- Deprecate some more methods that do not take a CryptoCurrency or CryptoValue.

AND-1216 remove duplicated price code

---

app/src/main/java/piuk/blockchain/android/ui/dashboard/DashboardPresenter.kt
app/src/main/java/piuk/blockchain/android/ui/dashboard/PieChartsState.kt
app/src/main/java/piuk/blockchain/android/ui/dashboard/adapter/PieChartDelegate.kt
app/src/main/res/drawable/rounded_non_spendable_button.xml
app/src/main/res/layout/item_pie_chart.xml
app/src/main/res/layout/item_pie_chart_bitcoin_unspendable.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/piuk/blockchain/android/ui/dashboard/DashboardPresenterTest.kt
coreui/src/main/java/piuk/blockchain/androidcoreui/utils/extensions/ViewExtensions.kt
coreui/src/main/res/values/colors.xml
coreui/src/test/java/piuk/blockchain/androidcoreui/utils/extensions/GoneIfTest.kt
coreui/src/test/java/piuk/blockchain/androidcoreui/utils/extensions/InvisibleIfTest.kt

When no-non-spendable, you don't see anything different:
With non-spendable:
Pressing the "button" toggles BTC/Fiat:

feat(Non-Spendable): AND-1217 Non-Spendable Chart UI

---

app/build.gradle
app/src/main/java/piuk/blockchain/android/injection/ApplicationComponent.java
app/src/main/java/piuk/blockchain/android/injection/Injector.java
app/src/main/java/piuk/blockchain/android/injection/KycModule.kt
app/src/main/java/piuk/blockchain/android/kyc/KycServerSideFeatureFlag.kt
app/src/test/java/piuk/blockchain/android/kyc/KycServerSideFeatureFlagTest.kt
kyc/build.gradle
kyc/src/main/java/com/blockchain/kyc/DisabledFeatureFlag.kt
kyc/src/main/java/com/blockchain/kyc/FeatureFlag.kt
kyc/src/test/java/com/blockchain/kyc/DisabledFeatureFlagTest.kt

- I've gone for a shared feature flag name with homebrew.
- We can make it country specific easily with a replacement implementation of `kyc.FeatureFlag`.
- Same story if we move from `options.json` at some point, it's no problem to create a replacement implementation of `kyc.FeatureFlag`.
- For new classes in the new module, I've started going for a base package of `com.blockchain.kyc`, so no `"piuk"` or `"android"`, bit cleaner and reflecting our domain better. What do you think?

AND-1241 KYC feature flag

---

app/build.gradle
app/secretsDefaults.properties

- To help new devs/public compilation
- A place we can commit new keys to (without necessarily real values/any value)
- Allows CI to build without `secrets.properties` (originally written for the Travis integration)

chore(Travis): AND-1188 Default secrets file

---

kyc/src/main/java/com/blockchain/kycui/countryselection/KycCountrySelectionFragment.kt
kyc/src/main/java/com/blockchain/kycui/search/CountrySelectionFilter.kt
kyc/src/main/java/com/blockchain/kycui/search/ListQueryObservable.kt
kyc/src/test/java/com/blockchain/kycui/search/CountrySelectionFilterTest.kt
kyc/src/test/java/com/blockchain/kycui/search/ListQueryObservableTest.kt

This is what I was suggesting, test drive the whole filtering logic, rather than untested logic in a `Fragment`.

feat(Homebrew): AND-1333 Test driven country filter

---

app/build.gradle
app/src/main/java/piuk/blockchain/android/data/bitcoincash/BchDataManager.kt
build.gradle
buildSrc/src/main/java/Dependencies.kt
buysell/build.gradle
buysellui/build.gradle
core/build.gradle
core/src/main/java/piuk/blockchain/androidcore/data/currency/CurrencyFormatManager.kt
core/src/main/java/piuk/blockchain/androidcore/data/currency/CurrencyState.java
core/src/main/java/piuk/blockchain/androidcore/data/metadata/MetadataManager.kt
core/src/main/java/piuk/blockchain/androidcore/data/payload/PayloadDataManager.kt
core/src/main/java/piuk/blockchain/androidcore/utils/annotations/Mockable.kt
coreui/build.gradle
kyc/build.gradle

- `:app` has the only `kapt` usage after this.
- `Mockable` and `allopen` was made defunct with `mock-maker-inline` a while back.

chore(Gradle): AND-1341 Remove allopen and unnecessary Kapts

---

build.gradle

Morph Dev app
===
Zero change (2nd run) `./gradlew :morph:morphDevApp:assembleDebug --scan`
Before: https://gradle.com/s/y55xk6l7kyvq4
```
BUILD SUCCESSFUL in 28s
109 actionable tasks: 33 executed, 72 from cache, 4 up-to-date
```
After: https://gradle.com/s/3qhvm5cwfzqvg
```
BUILD SUCCESSFUL in 3s
109 actionable tasks: 109 up-to-date
```
Didn't even have to go to the local cache for any tasks.
Main App
===
Zero change (2nd run): `./gradlew :app:assembleEnvProdDebug --scan`
Before: https://gradle.com/s/7t6jrcaxc4koy
```
BUILD SUCCESSFUL in 1m 57s
208 actionable tasks: 66 executed, 134 from cache, 8 up-to-date
```
After: https://gradle.com/s/bf2xemzm2cbtc
```
BUILD SUCCESSFUL in 27s
208 actionable tasks: 10 executed, 198 up-to-date
```
App with no cache
===
Zero change (2nd run): `./gradlew …

chore(Build): AND-1396 Fix incremental build speed

---

kyc/src/main/java/com/blockchain/injection/kycModule.kt
kyc/src/main/java/com/blockchain/kyc/datamanagers/nabu/NabuAuthenticator.kt
kyc/src/main/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManager.kt
kyc/src/test/java/com/blockchain/kyc/datamanagers/nabu/NabuDataManagerAsAuthenticatorTest.kt
nabu/src/main/kotlin/com/blockchain/nabu/Authenticator.kt

- Add general Nabu authenticator interface - this is not fully generic, but I don't see any value in that just yet and the `Authenticator` interface is in the nabu package.
- After struggling to detach Auth from the data manager (mainly due to tests being hard to refactor), I ended up wrapping it.

feat(HomeBrew): AND-1335 auth refactor part3

---

app/src/main/java/piuk/blockchain/android/ui/account/ItemAccount.kt
app/src/main/java/piuk/blockchain/android/ui/shapeshift/newexchange/NewExchangeActivity.kt
app/src/test/java/piuk/blockchain/android/ui/chooser/WalletAccountHelperAccountListingAdapterTest.kt
common/network/src/main/kotlin/com/blockchain/serialization/JsonSerializable.kt
coreui/src/main/java/com/blockchain/koin/coreUiModule.kt
coreui/src/main/java/com/blockchain/ui/chooser/AccountChooserActivity.kt
coreui/src/main/java/com/blockchain/ui/chooser/AccountChooserAdapter.kt
coreui/src/main/java/com/blockchain/ui/chooser/AccountChooserItem.kt
morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeActivity.kt
wallet/src/main/java/com/blockchain/serialization/JsonSerializableAccount.kt
wallet/src/main/java/info/blockchain/wallet/coin/GenericMetadataAccount.java
wallet/src/main/java/info/blockchain/wallet/contacts/data/Contact.java
wallet/src/main/java/info/blockchain/wallet/ethereum/EthereumAccount.java
wallet/src/main/java/info/blockchain/wallet/payload/data/Account.java
wallet/src/main/java/info/blockchain/wallet/payload/data/LegacyAddress.java

- Just logs the result of the selection
- Identical to shapeshift's one, I'd already made this general (available in `:coreui`) restyle can come later, and we should discuss if we even want different user experience from different places in the app. This one is used for sending and receiving as well for example.

feat(HomeBrew): AND-1374 Use existing account picker in HomeBrew

---

common/network/src/main/kotlin/com/blockchain/network/websocket/AfterOpenWebSocket.kt
common/network/src/main/kotlin/com/blockchain/network/websocket/WebSocket.kt
common/network/src/test/kotlin/com/blockchain/network/websocket/AfterOpenWebSocketTest.kt
common/network/src/test/kotlin/com/blockchain/network/websocket/WebSocketOpenAsDisposableTests.kt

- Disposable web sockets make it easier to clean up sockets
- After Open is useful for triggering authentication after connection

 feat(HomeBrew): AND-1339 Disposable and After Open WebSocket

---

morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/detail/HomebrewTradeDetailActivity.kt
morph/ui/src/main/res/layout/activity_homebrew_trade_detail.xml
morph/ui/src/main/res/values/strings.xml

Trade detail, Order ID removed from toolbar ad added as new row
Status explained text added to screen and strings. 
TODO: populate the screen with real data from endpoint + change the status text according to the order status.

feat(HomeBrew): AND-1386 Trade detail

---

morph/common/src/main/java/com/blockchain/morph/exchange/mvi/ExchangeViewModel.kt
morph/common/src/test/java/com/blockchain/morph/exchange/mvi/ExchangeViewModelValidityTest.kt
morph/ui/src/main/java/com/blockchain/morph/ui/homebrew/exchange/ExchangeFragment.kt
morph/ui/src/main/res/drawable/exchange_button_background.xml
morph/ui/src/main/res/layout/fragment_homebrew_exchange.xml
morph/ui/src/main/res/values/exchange_styles.xml

- Button is disabled and grey when the last quote doesn't match the value the user has typed.
- This happens when the quote has not yet been returned
- Or the quote was unable to be returned for whatever reason

feat(HomeBrew): AND-1350 Disable Exchange button when a quote is not valid

---

app/src/main/java/piuk/blockchain/android/ui/receive/WalletAccountHelper.kt

Done bare minimum here. Would like to revamp the balance stuff to use `CryptoValue`, `FiatValue` and `Money` sometime.

feat(Homebrew): AND-1448 Remove brackets from account balances value
